language: python
matrix:
    include:
        - name: "Python 3.6 on Linux"
          python: 3.6
        - name: "Python 3.7 on Linux"
          python: 3.7
        - name: "Python 3.7 on macOS"
          os: osx
          osx_image: xcode11
          language: shell
git:
    quiet: true
before_install:
- sudo rm -f /etc/boto.cfg
install:
- pip install -r requirements.txt
- pip install coverage
- pip install coveralls
script:
- python3 setup.py test || python setup.py test
- coverage run --source=psiturk setup.py test
after_success: coveralls
deploy:
    # test pypi pip deployment
#  - provider: pypi
#    server: https://test.pypi.org/legacy/
#    user: nyuccl
#    password:
#      secure: h8nh6ooykI7eniajVkE/MYxZgyZoxcKRODhFWUwjlSHRmUV2tW/n2i/4MYJvMQXqiBgO64nOPmNhNH0mhYY+GbwyinAThRn3xhPIUfO8tV+edpzlzSwnGT+xSRINoUaGZfrs5UqCPVS7Ff5EB4SYRfrYBoV2VA5sx1XxoKKPkU4=
#    on:
#      tags: false
#      branch: master
         
    # production pypi
    provider: pypi
    user: nyuccl
    password:
      secure: h8nh6ooykI7eniajVkE/MYxZgyZoxcKRODhFWUwjlSHRmUV2tW/n2i/4MYJvMQXqiBgO64nOPmNhNH0mhYY+GbwyinAThRn3xhPIUfO8tV+edpzlzSwnGT+xSRINoUaGZfrs5UqCPVS7Ff5EB4SYRfrYBoV2VA5sx1XxoKKPkU4=
    skip_existing: true
    on:
      tags: true
      branch: master
